[package]
name = "vdf"
description = "A tool for interrogating files that use Valve's binary VDF format."
version = "0.1.0"
edition = "2021"

[dependencies]
vdfr = { path = "../vdfr" }
clap = { version = "4", features = ["cargo"] }
